.\" Manpage for simecg.
.\" Contact digiplan.pt@gmail.com to correct errors or typos.
.TH man 1 "8 Feb 2015" "" "simecg man page"
.SH NAME
simecg
.SH SYNOPSIS
simECG is an ECG simulator for both training and assessment purposes.
.SH DESCRIPTION
simECG has the ability to display several pre-defined rhythms for training purposes, such as rhythm and conduction disturbances. Additionally, a number of settings can be altered in order to create different training experiences for different levels of user proficiency. With the release of this version, in Open Source format, the authors put in practical application their ideal that education (and training, in this case) should not be a commercial tool accessible to some but rather a free collaborative tool available for those who seek knowledge.This project will always be unfinished, and for that reason we count with your comments and feedback to improve it. Please write you feedback by mail or place in the forum. 
.SH OPTIONS
The simecg does not take any options.
.SH BUGS
No known bugs.
.SH "SEE ALSO"
http://simecg.sourceforge.net/
